Fix update dynamic registration bug (#106)
A parsing bug of the CN causes update of OIDC client to fail with a 500
with the stacktrace

```
java.lang.IllegalArgumentException: badly formatted directory string
	at org.bouncycastle.asn1.x500.style.IETFUtils.rDNsFromString(Unknown Source)
	at org.bouncycastle.asn1.x500.style.BCStyle.fromString(Unknown Source)
	at org.bouncycastle.asn1.x500.X500Name.<init>(Unknown Source)
	at org.bouncycastle.asn1.x500.X500Name.<init>(Unknown Source)
	at com.forgerock.openbanking.aspsp.as.api.registration.dynamic.DynamicRegistrationApiController.verifyRegistrationRequest(DynamicRegistrationApiController.java:383)
	at com.forgerock.openbanking.aspsp.as.api.registration.dynamic.DynamicRegistrationApiController.updateClient(DynamicRegistrationApiController.java:221)
```

This change fixes the parsing